pub mod ast;
pub mod axiom_registry;
pub mod bridge;
pub mod bridge_assumption;
pub mod conservative_extension;
pub mod checker;
pub mod certificate;
pub mod certificate_audit;
pub mod diagnostics;
pub mod equality;
pub mod function;
pub mod function_contract;
pub mod induction;
pub mod logic;
pub mod ids;
pub mod meta_level;
pub mod metatheory_closure;
pub mod metatheory_foundation;
pub mod module_interface;
pub mod module_system;
pub mod parser;
pub mod partiality;
pub mod passes;
pub mod passport;
pub mod passport_rules;
pub mod policy;
pub mod proof_context;
pub mod runtime;
pub mod sequence;
pub mod traversal;
pub mod recursion;
pub mod termination_budget;
pub mod resolve;
pub mod rewrite_normalization;
pub mod soundness;
pub mod standard_prelude;
pub mod prelude_eval;
pub mod statement;
pub mod structural;
pub mod structural_elimination;
pub mod substitution;
pub mod tactic;
pub mod theorem_dependency;
pub mod trusted_base;

pub use ast::*;
pub use axiom_registry::{audit_metatheory_dependencies, axiom_decl, axiom_registry, axiom_registry_passport, dependency_entry_from_axiom, dependency_entry_from_passport, export_axiom_registry_text, metatheory_dependency_audit_passport, render_metatheory_dependency_audit_report, require_declared_axiom, require_verified_metatheory_dependency_audit, AxiomDecl, AxiomKind, AxiomRegistry, DependencyAuditStatus, DependencyEntry, DependencyUseKind, MetatheoryDependencyAuditReport};
pub use bridge::{bridge_law, find_bridge, has_bridge, profile_for_decl, BridgeLaw, BridgeProfile};
pub use bridge_assumption::{boundary_assumption_from_bridge_profile, boundary_assumption_from_passport, export_soundness_boundary_ledger, render_soundness_boundary_ledger, require_verified_soundness_boundary_ledger, soundness_boundary_ledger, soundness_boundary_ledger_passport, BoundaryAssumptionEntry, BoundaryAssumptionKind, SoundnessBoundaryLedgerReport, SoundnessBoundaryStatus};
pub use certificate::{certificate_from_closure, certificate_from_tactic_report, compute_certificate_fingerprint, verify_certificate_against_theorem, ProofCertificate, ProofCertificateStatus};
pub use certificate_audit::{audit_certificate_against_theorem, export_certificate_text, export_certificate_text_unchecked, render_certificate_audit_report, CertificateAuditReport, CertificateAuditStatus};
pub use conservative_extension::{audit_conservative_extension, conservative_extension_audit_passport, export_conservative_extension_audit_report, preserved_theorem, render_conservative_extension_audit_report, require_verified_conservative_extension_audit, ConservativeExtensionAuditReport, ConservativeExtensionStatus, PreservedTheorem};
pub use checker::{CheckReport, Checker};
pub use diagnostics::{Diagnostic, DiagnosticKind, Severity, SourceSpan};
pub use equality::{apply_rewrite_rule, axiom_eq_proof, eq_proof_decl, eq_proof_from_static_proof, equality_proposition, reflexive_eq_proof, require_eq_proof, require_rewrite_rule, rewrite_certificate_passport, rewrite_rule_decl, rewrite_rule_from_eq_proof, rewrite_trace, EqProofDecl, RewriteDirection, RewriteRuleDecl, RewriteStep, RewriteTrace};
pub use ids::{BridgeId, FileId, IdAllocator, ModuleId, ProofId, TheoryId, TypeId, ValueId};
pub use logic::{bound_variable, export_logical_formula, export_quantified_formula, formula_atom, formula_from_passport, logical_formula, logical_formula_passport, quantified_formula, quantified_formula_passport, require_logical_formula, require_quantified_formula, BoundVariable, LogicalConnective, LogicalFormula, QuantifiedFormula, QuantifierKind};
pub use induction::{induction_base_case, induction_base_case_decl, induction_proof_decl, induction_step_case, induction_step_case_decl, nat_base_case_proposition, nat_induction_conclusion, nat_induction_proof, nat_induction_scheme, nat_induction_scheme_decl, nat_step_case_proposition, require_induction_base_case, require_induction_proof, require_induction_step_case, require_nat_induction_scheme, theorem_from_induction_proof, InductionBaseCaseDecl, InductionProofDecl, InductionStepCaseDecl, NatInductionSchemeDecl};
pub use meta_level::{meta_level_passport, meta_quote_passport, object_level_passport, required_observer_level, validate_meta_observer, MetaAccess, MetaLevelContext, MetaLevelIndex, MetaStage};
pub use metatheory_closure::{closed_closure_obligation, closure_obligation, export_metatheory_closure_report, metatheory_closure_report, metatheory_closure_report_passport, open_closure_obligation, render_metatheory_closure_report, require_closed_metatheory_closure, ClosureObligation, ClosureObligationKind, MetatheoryClosureReport, MetatheoryClosureStatus};
pub use metatheory_foundation::{export_metatheory_foundation_exit_report, metatheory_exit_criterion, metatheory_exit_criterion_from_passport, metatheory_exit_criterion_from_trusted_base_report, metatheory_foundation_exit_passport, metatheory_foundation_exit_report, render_metatheory_foundation_exit_report, require_metatheory_foundation_ready, required_metatheory_exit_criteria, MetatheoryExitCriterion, MetatheoryExitCriterionKind, MetatheoryExitCriterionStatus, MetatheoryFoundationExitReport, MetatheoryFoundationStatus};
pub use module_interface::{audit_module_import, export_module_interface_text, module_import_audit_passport, module_interface, module_interface_passport, public_interface_symbols, render_module_import_audit_report, require_interface_symbol, require_verified_module_import_audit, InterfaceSymbol, ModuleImportAuditReport, ModuleImportAuditStatus, ModuleInterface};
pub use module_system::{build_import_graph, import_decl, import_graph_passport, imported_public_symbols, module_export_passport, module_manifest, module_manifest_passport, private_export, public_export, require_public_export, validate_module_manifest, ExportDecl, ExportVisibility, ImportDecl, ImportEdge, ImportGraph, ModuleManifest};
pub use parser::{parse_expr, parse_module};
pub use partiality::*;
pub use passes::{run_frontend_passes, FrontendPassOutput, PassId, PassPipelineReport, PassReport, PassStatus};
pub use passport::*;
pub use policy::CheckPolicy;
pub use proof_context::{assume_hypothesis, close_proof_by_axiom, close_proof_with_static_proof, open_proof_context, proof_obligation_for_goal, Hypothesis, HypothesisId, HypothesisSet, ProofClosure, ProofClosureStatus, ProofContext, ProofObligation, TacticStep};
pub use runtime::{RunReport, Runtime, RuntimeValue};
pub use sequence::*;
pub use traversal::*;
pub use recursion::*;
pub use termination_budget::*;
pub use resolve::{resolve_module, ResolvedBridge, ResolvedImport, ResolvedModule, ResolvedTheory, ResolvedValue, Resolver, SymbolTable};
pub use rewrite_normalization::{audit_rewrite_normalization_report, export_rewrite_normalization_report, export_rewrite_normalization_report_unchecked, normalize_with_rewrite_rules, RewriteNormalizationReport, RewriteNormalizationStatus};
pub use soundness::{BridgeSoundnessProfile, SoundnessIssue, SoundnessSummary};
pub use substitution::{alpha_equivalence_passport, alpha_equivalence_report, alpha_rename_quantified_formula, export_alpha_equivalence_report, export_substitution_report, export_variable_scope_report, require_alpha_equivalent, substitution_report, substitution_report_passport, substitution_source_from_passport, variable_scope_passport, variable_scope_report, AlphaEquivalenceReport, AlphaEquivalenceStatus, SubstitutionReport, SubstitutionStatus, VariableOccurrence, VariableOccurrenceKind, VariableScopeReport};
pub use structural::*;
pub use structural_elimination::*;
pub use standard_prelude::*;
pub use prelude_eval::*;
pub use statement::{axiom_theorem, goal_decl, goal_passport, hypothesis_decl, hypothesis_passport, proposition_of, require_statement_like, require_static_proof, statement_decl, statement_passport, theorem_decl, theorem_from_static_proof, DeclarationKind, GoalDecl, HypothesisDecl, StatementDecl, TheoremDecl};
pub use tactic::{execute_tactic_script, TacticCommand, TacticScript, TacticScriptReport, TacticScriptStatus, TacticScriptStep, TacticStepIndex};
pub use theorem_dependency::{export_global_metatheory_inventory, global_metatheory_inventory, global_metatheory_inventory_passport, render_global_metatheory_inventory, require_verified_global_metatheory_inventory, theorem_dependency_edge, theorem_dependency_node_from_passport, GlobalMetatheoryInventoryReport, MetatheoryInventoryStatus, TheoremDependencyEdge, TheoremDependencyNode, TheoremDependencyNodeKind};
pub use trusted_base::{export_trusted_base_closure, render_trusted_base_closure, require_closed_trusted_base_closure, trusted_base_closure, trusted_base_closure_passport, trusted_base_evidence_from_axiom_registry, trusted_base_evidence_from_conservative_extension, trusted_base_evidence_from_dependency_audit, trusted_base_evidence_from_global_inventory, trusted_base_evidence_from_metatheory_closure, trusted_base_evidence_from_passport, trusted_base_evidence_from_soundness_boundary_ledger, TrustedBaseClosureReport, TrustedBaseClosureStatus, TrustedBaseEvidence, TrustedBaseEvidenceKind};

pub use function::*;
pub use function_contract::*;
